--DATA groupe
INSERT INTO `groupe` (`id`, `Label`) VALUES
(1, 'Admin'),
(2, 'User');
COMMIT;

--changements a faire
dans rating mettre date à datetime
enlever rating de la table User
ajouter une colonne image pour product

https://www.creativejuiz.fr/blog/tutoriels/personnaliser-aspect-boutons-radio-checkbox-css
https://fr.w3docs.com/snippets/css/comment-styler-une-case-a-cocher-avec-css.html#:~:text=La%20case%20%C3%A0%20cocher%20est%20l%27une%20des%20formulaires,vous%20pouvez%20simplement%20styler%20votre%20cases%20%C3%A0%20cocher.